import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";
import SupportAgent from "./components/SupportAgent";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
     className="flex flex-col min-h-screen"
      >
        <div>
          <main className="flex-grow">
          {children}
      
          </main>
          <Footer />
          <SupportAgent />
          </div>
      </body>
    </html>
  );
}
